### ISSUE TITLE
[Edge/Docs] The selection is incorrect after putting the caret before the heading 1

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-heading#87] opened 2017-10-02 10:27 UTC
## Steps to reproduce
1. Go to https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/headings.html.
2. Click on the blank space before the `Heading 1`.
3. Type something.

## Current result
The selection is incorrect, text appears above the `Heading 1`.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/31073576-c1af57ee-a76c-11e7-8d95-918379cb915e.gif)

## Other information
OS: Windows 10
Browser: Edge 16
Release: 0.11.0

**Comment by Reinmar** [comment] 2017-10-02 10:37
I think it may be the problem with styling again. I'll check it.

**Comment by Reinmar** [comment] 2017-10-02 11:08
It should be fixed by https://github.com/ckeditor/ckeditor5-engine/pull/1151.

**Closed** 2017-10-02 11:10 UTC
Labels: candidate:1.0.0, status:confirmed, type:bug

**Comment by Reinmar** [comment] 2017-10-02 11:12
Ha, surprise. Turns out that this issue was caused by styling, as I initially thought and was fixed by https://github.com/ckeditor/ckeditor5/commit/d84700561ab032db44cc456fb867b7cd55ed6a38.

However, the PR in the engine may improve this situation even further by securing that regardless of styling the selection may only end up in the heading and not outside.
